### ISSUE TITLE
Overpass API rate limit

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/openvegemap#17]
The Overpass API only allows only two simultaneous connections, we need to find a way around that (Cache? Queue?).

**Comment by Rudloff** [comment]
Fixed by using leaflet-layer-overpass

**Comment by Rudloff** [comment]
Yes, the data is currently fetched from the Overpass API everytime.
I agree it would be nice to cache the data browser-side, but IMHO this should be handled by leaflet-overpass-layer (see https://github.com/GuillaumeAmat/leaflet-overpass-layer/issues/15).

**Comment by AntoineJaury** [comment]
I was more thinking about a cache server-side (on OpenVegeMap server) than browser-side. But both are good ideas I think.

**Comment by Rudloff** [comment]
I get what you are saying, but currently OVM is a full client-side app (except for the editor) and I would prefer to keep it that way.
(It means the Android app connects directly to the OSM API without needing my server, for example.)

**Comment by AntoineJaury** [comment]
I understand. If this is a matter of time for you, I did it simply on CartoVrac with a script that performs the Overpass API once a day thanks to a CRON. Here is the script: [refreshCache.sh](https://github.com/vivreanantes/cartovrac/blob/master/refreshCache.sh) and the apps target directly the JSON file kept in cache on my server rather than from Overpass API. So feel free to reuse the script if needed.

At the beginning I didn't have the CRON and the script, I just uploaded a new JSON file from time to time but it was not really sustainable.
