### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#24]
Currently a minimum zoom level is too high. Please add a possibility to set zoom parameter to 10 or 5, for example.

**Comment by Rudloff** [comment]
The main reason why zoom level is limited, is because [leaflet-overpass-layer](https://github.com/kartenkarsten/leaflet-layer-overpass) won't load any data when zoom is < 15 in order to avoid being rate limited by the OSM API.

We could allow lower levels of zoom, but I'm afraid users won't understand why they don't get any data if they don't zoom enough.

**Comment by dimqua** [comment]
If user do not live in France, it's hard for him to use the map at the first time. Especially if he can't or doesn't want to use geolocation feature for some reason. 

Beside that it's not very useful to scroll the map, if you live in reatively big city, such as Moscow in my case.

> I'm afraid users won't understand why they don't get any data if they don't zoom enough.

I suggest to set the default zoom level to 15.

**Comment by Rudloff** [comment]
Thanks for your suggestion. This will be included in the next release.
