### ISSUE TITLE
Multi-choice filters

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#30]
Please allow multiple choices for the filters. Useful examples include:
* vegan friendly + vegetarian friendly;
* vegan friendly + vegetarian only.

**Comment by Rudloff** [comment]
Hello,
I don't want to make the filters too complex.
Also I find your combinations a little bit confusing:
* The current *vegetarian friendly* filter already includes vegan friendly, since what is suitable for vegans is also suitable for vegetarians).
* What should "vegan friendly + vegetarian only" display ? If it displays only restaurants that are vegan or vegetarian, then it is basically the current *vegetarian only* filter.

(I might need to make it more clear that vegetarian filters include vegan restaurants though.)

**Comment by dimqua** [comment]
Yes, thanks for clarification.
>What should "vegan friendly + vegetarian only" display ?

Vegetarian restaurants with vegan options available.

**Comment by Rudloff** [comment]
I guess this is a valid use case.
I will think about a better way to present the filters.

**Comment by Rudloff** [comment]
@dimqua Would something like this be OK for you?
![capture d ecran 2017-08-26 a 20 01 31](https://user-images.githubusercontent.com/840125/29743838-765ac5de-8a99-11e7-9106-8ba8934cd658.png)
I think I will also add some tooltips to explain what each filter does exactly.

**Comment by dimqua** [comment]
Yes, thanks!
