### ISSUE TITLE
Filters/list: why "vegan only" option but no "vegetarian only"?

### ISSUE THREAD

**Issue by axelsimon** [Rudloff/openvegemap#56]
Hi,
I'm a bit surprised, OpenVegeMap showed me a restaurant listed as "vegetarian" which is really a general place that has a few veggie options.
I think it would make sense to be able to separate these places from fully vegetarian places. The way OpenStreetMap has `diet:vegetarian=yes` and `diet:vegetarian=only` for instance.

Alse, OpenVegeMap already differentiates between vegan and vegan only, so it would be consistent to do the same for vegetarian.

Hope this helps.

**Comment by axelsimon** [comment]
Maybe even show this "vegetarian only" option instead of the "meat only" option, which is a bit out of place in a veggie map.

**Comment by Rudloff** [comment]
Hello,

I you don't want "vegetarian-friendly" restaurants, you can simply disable them in the *Filters* menu.
I guess they could have a different icon, I just don't want to add too many different markers.

> which is really a general place that has a few veggie options.

In some cities with very few vegetarian food I can be really useful to find a place where you can eat at all, which is why we display these restaurants.
(But I get that people have different needs, which is why we have the *Filters* menu.)

> the "meat only" option, which is a bit out of place in a veggie map.

This filter is disabled by default, but it is useful for contributors that want to check if we already know that a restaurant is not vegetarian, so they don't bother checking it.

**Comment by Rudloff** [comment]
I added a different marker for "vegetarian only", it will be in the next release.
