### ISSUE TITLE
Cuisine: tag support

### ISSUE THREAD

**Issue by dimqua** [Rudloff/openvegemap#62]
Do the map displays nodes that have a `cuisine:vegan` or `cuisine:vegetarian` tags, but don't have a `diet:` tag?

**Comment by Rudloff** [comment]
No, because (as explained [on the wiki](https://wiki.openstreetmap.org/wiki/Key:cuisine#Cuisine_.28type_of_food.29)) this is not a correct way to tag vegan/vegetarian restaurants.
IMHO, these should be fixed to use `diet:` instead.

**Comment by dimqua** [comment]
But why not display them (optionally at least)? I mean, there're A LOT of such places (see [searchosm.com](https://searchosm.com/), it's nearly impossible to fix all of them in the near future.

**Comment by Rudloff** [comment]
Because if I display them, they will never be fixed :wink: 
Also, adding new conditions to the Overpass query quickly slows it down so I would like to avoid that.

I asked on the wiki if it would be possible to fix this with a mass-edit: https://wiki.openstreetmap.org/wiki/Talk:Key:cuisine#Mass_convert_vegan_and_vegetarian_values

**Comment by dimqua** [comment]
OK, I have an another question. What if a place tagged as `diet:vegan=limited`, for example, how is it treated? Ignored?

**Comment by Rudloff** [comment]
It will be displayed but considered non-vegan (OVM basically thinks any unknown value equals `no`).
See for example: https://openvegemap.netlib.re/#zoom=18&lat=50.0484386&lon=8.6776254

I strongly advise trying to get these values added to the wiki (see discussion [here](https://wiki.openstreetmap.org/wiki/Talk:Key:diet#add_.27limited.27_value)) before using them.
